# Generated by Django 4.0.3 on 2022-04-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNo', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=25)),
                ('team', models.CharField(max_length=10)),
                ('customercode', models.CharField(max_length=10)),
                ('assigned', models.CharField(max_length=255)),
                ('mandays', models.IntegerField(default='0', null=True)),
                ('abap', models.CharField(default='ABAP', max_length=10)),
                ('amandays', models.IntegerField(default='0', null=True)),
                ('description', models.TextField()),
                ('changereason', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_targetclose', models.DateField(blank=True, null=True)),
                ('date_close', models.DateField(blank=True, null=True)),
                ('requester', models.CharField(max_length=255)),
                ('reasoncode', models.CharField(blank=True, max_length=50, null=True)),
                ('classt', models.CharField(max_length=50)),
            ],
        ),
    ]
