# Generated by Django 4.0.3 on 2022-08-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_month_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(default='00.0000', max_length=30, null=True, unique=True)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNo', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('team', models.CharField(blank=True, max_length=10, null=True)),
                ('customercode', models.CharField(blank=True, max_length=10, null=True)),
                ('assigned', models.CharField(blank=True, max_length=255, null=True)),
                ('mandays', models.DecimalField(blank=True, decimal_places=1, default='0.00', max_digits=5, null=True)),
                ('abap', models.CharField(default='ABAP', max_length=10)),
                ('amandays', models.DecimalField(blank=True, decimal_places=1, default='0.00', max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('changereason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_targetclose', models.DateField(blank=True, null=True)),
                ('date_close', models.DateField(blank=True, null=True)),
                ('requester', models.CharField(blank=True, max_length=255, null=True)),
                ('reasoncode', models.CharField(blank=True, max_length=50, null=True)),
                ('classt', models.CharField(blank=True, default='Inactive', max_length=10, null=True)),
                ('flag', models.BooleanField(default=False)),
                ('month_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.ticket_month_year', to_field='month_year')),
            ],
        ),
    ]
