# Generated by Django 4.0.3 on 2022-08-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_close',
            field=models.DateField(blank=True, default='1999-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateField(blank=True, default='1999-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_targetclose',
            field=models.DateField(blank=True, default='1999-01-01', null=True),
        ),
    ]
