# Generated by Django 4.0.3 on 2022-04-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_ticket_amandays_alter_ticket_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
