# Generated by Django 4.0.3 on 2022-05-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
