# Generated by Django 4.0.3 on 2022-06-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_ticket_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_close',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_targetclose',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
