# Generated by Django 4.0.3 on 2022-08-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_ticket_date_close_alter_ticket_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_ABAP_manday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNo', models.CharField(max_length=20)),
                ('amandays', models.DecimalField(blank=True, decimal_places=1, default='0.00', max_digits=5, null=True)),
            ],
        ),
    ]
