# Generated by Django 4.0.3 on 2022-06-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_ticket_date_close_alter_ticket_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_close',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_targetclose',
            field=models.DateField(blank=True, null=True),
        ),
    ]
