# Generated by Django 4.0.3 on 2022-08-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_ticket_abap_manday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket_ABAP_manday',
            new_name='Ticket_abap_mandays',
        ),
    ]
