# Generated by Django 4.0.3 on 2022-06-02 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_ticket_date_close_alter_ticket_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_month_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(default='00.0000', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='month_year',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.ticket_month_year'),
            preserve_default=False,
        ),
    ]
