# Generated by Django 4.0.3 on 2022-06-02 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_ticket_month_year_ticket_month_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='month_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Home.ticket_month_year', to_field='month_year'),
        ),
        migrations.AlterField(
            model_name='ticket_month_year',
            name='month_year',
            field=models.CharField(default='00.0000', max_length=30, unique=True),
        ),
    ]
