# Generated by Django 4.0.3 on 2022-06-09 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_ticket_month_year_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='month_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.ticket_month_year', to_field='month_year'),
        ),
    ]
