# Generated by Django 4.0.3 on 2022-06-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_ticket_month_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='amandays',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mandays',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5, null=True),
        ),
    ]
