# Generated by Django 4.0.3 on 2022-06-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_ticket_amandays_alter_ticket_mandays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='amandays',
            field=models.DecimalField(blank=True, decimal_places=1, default='0.00', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mandays',
            field=models.DecimalField(blank=True, decimal_places=1, default='0.00', max_digits=5, null=True),
        ),
    ]
