# Generated by Django 4.0.3 on 2022-08-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_ticket_month_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='month_year',
            field=models.ForeignKey(default='00.0000', on_delete=django.db.models.deletion.SET_DEFAULT, to='Home.ticket_month_year', to_field='month_year'),
        ),
    ]
