# Generated by Django 4.0.3 on 2022-08-17 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_ticket_month_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='month_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.ticket_month_year', to_field='month_year'),
        ),
        migrations.AlterField(
            model_name='ticket_month_year',
            name='month_year',
            field=models.CharField(default='00.0000', max_length=30, null=True, unique=True),
        ),
    ]
